import type { Session } from "@/lib/types";

export const sessions: Session[] = [
  {
    id: "aurora",
    title: "Aurora — Brand Film",
    description:
      "A 90-second cinematic brand film shot across Reykjavík at golden hour and blue hour. Calm, premium, human.",
    date: "Jun 24, 2026",
    location: "Reykjavík, IS",
    hue: 256,
    shots: [
      {
        id: "s1",
        title: "Establishing drone over the harbor",
        description:
          "Slow aerial push over the harbor as the sun breaks the horizon, boats catching the first light. Sets the scale and the mood.",
        type: "drone",
        movement: "crane",
        durationSec: 8,
        location: "Old Harbor",
        lens: "24mm",
        priority: "essential",
        status: "filmed",
      },
      {
        id: "s2",
        title: "Hero walks toward camera",
        description:
          "Medium tracking shot, hero walks the waterfront with steam rising behind. Backlit, shallow depth.",
        type: "medium",
        movement: "dolly",
        durationSec: 6,
        location: "Waterfront",
        lens: "50mm",
        priority: "essential",
        status: "filmed",
      },
      {
        id: "s3",
        title: "Close-up — hands wrap the product",
        description:
          "Tight close-up of hands wrapping the product in linen. Macro-adjacent detail, warm practical light.",
        type: "close-up",
        movement: "static",
        durationSec: 4,
        location: "Studio A",
        lens: "85mm",
        priority: "essential",
        status: "to_film",
      },
      {
        id: "s4",
        title: "POV — opening the door to the studio",
        description:
          "First-person POV pushing through the studio door into warm light. Quick, immersive transition beat.",
        type: "pov",
        movement: "handheld",
        durationSec: 3,
        location: "Studio entrance",
        lens: "18mm",
        priority: "optional",
        status: "to_film",
      },
      {
        id: "s5",
        title: "Wide — the team at work",
        description:
          "Wide of the full team mid-build, layered foreground and background activity. Shows craft and scale.",
        type: "wide",
        movement: "pan",
        durationSec: 7,
        location: "Workshop",
        lens: "35mm",
        priority: "essential",
        status: "to_film",
      },
      {
        id: "s6",
        title: "Macro — texture of the material",
        description:
          "Extreme macro across the material's grain, rack focus revealing fibers. Tactile, sensory beat.",
        type: "macro",
        movement: "tilt",
        durationSec: 4,
        location: "Studio A",
        lens: "100mm macro",
        priority: "optional",
        status: "abandoned",
      },
      {
        id: "s7",
        title: "Drone pull-back reveal at blue hour",
        description:
          "Reverse aerial pulling back from the lit studio window to the city skyline at blue hour. Closing breath.",
        type: "drone",
        movement: "crane",
        durationSec: 9,
        location: "Rooftop",
        lens: "24mm",
        priority: "essential",
        status: "to_film",
      },
      {
        id: "s8",
        title: "Logo — close on the embossed mark",
        description:
          "Close static on the embossed logo as a hand brushes past. Final stamp before the end card.",
        type: "close-up",
        movement: "static",
        durationSec: 3,
        location: "Studio A",
        lens: "85mm",
        priority: "essential",
        status: "to_film",
      },
    ],
  },
  {
    id: "nimbus",
    title: "Nimbus Sneaker — Launch Teaser",
    description: "A punchy 20-second product teaser. High energy, hard light, fast cuts on a seamless cyc.",
    date: "Jul 2, 2026",
    location: "Studio B",
    hue: 350,
    shots: [
      {
        id: "n1",
        title: "Wide — sneaker drops into frame",
        description: "Wide on the cyc as the sneaker drops and bounces once, hard shadow. Cold open.",
        type: "wide",
        movement: "static",
        durationSec: 2,
        location: "Studio B",
        lens: "35mm",
        priority: "essential",
        status: "filmed",
      },
      {
        id: "n2",
        title: "Macro — lace tightens",
        description: "Macro on the lace cinching through the eyelets, snap zoom. Detail and tension.",
        type: "macro",
        movement: "static",
        durationSec: 2,
        location: "Studio B",
        lens: "100mm macro",
        priority: "essential",
        status: "filmed",
      },
      {
        id: "n3",
        title: "Turntable hero spin",
        description: "Slow turntable hero of the sneaker, rim-lit, rotating 360 over the beat.",
        type: "close-up",
        movement: "dolly",
        durationSec: 5,
        location: "Studio B",
        lens: "50mm",
        priority: "essential",
        status: "to_film",
      },
    ],
  },
  {
    id: "makers",
    title: "Makers — Documentary",
    description: "Observational mini-doc following a ceramics studio across a single working day. Honest, handheld.",
    date: "Jun 28, 2026",
    location: "Lisbon, PT",
    hue: 152,
    shots: [
      {
        id: "m1",
        title: "Handheld — hands at the wheel",
        description: "Intimate handheld over the shoulder as clay rises on the wheel. Natural window light.",
        type: "close-up",
        movement: "handheld",
        durationSec: 10,
        location: "Studio",
        lens: "35mm",
        priority: "essential",
        status: "filmed",
      },
      {
        id: "m2",
        title: "Wide — the studio wakes up",
        description: "Static wide of the empty studio as morning light moves across the shelves.",
        type: "wide",
        movement: "static",
        durationSec: 8,
        location: "Studio",
        lens: "24mm",
        priority: "optional",
        status: "to_film",
      },
    ],
  },
];
